Maintenance
infn-datacloud/orchestrator-dashboard pull request #28
Opened 2024-11-20 14:23 UTC by ettore-infn

2024-12-04 17:05 UTC, giosava94 requested changes

2024-12-04 17:05 UTC, giosava94 commented on app/deployments/routes.py
> +    source_template = tosca_info[dep.selected_template]
In generale dalla riga 1583, il codice è praticamente uguale a create_dep (dalla riga 1491), cambia solo selected_template che in retrydep è dep.selected_template e il fatto che manca la parte dell'aggiunta della SLA policy (da valutare se non ci stiamo perdendo informazioni).
Penso che l'ideale sarebbe avere un'unica funzione che racchiude il codice dalla 1491 a 1540 e che quella funzione venga utilizzata sia da createdep che da retrydep.

2024-12-05 14:04 UTC, lgiommi commented on app/deployments/routes.py
> +        errors.append("Bucket names must begin and end with a letter or number.")
Qua in realtà l'inizio del nome del bucket è appunto un uuid quindi il nome scelto dall'utente può non per forza iniziare con una lettera o numero

2024-12-05 14:09 UTC, lgiommi commented on app/deployments/routes.py
> +    # Rule 6: Must not start with prohibited prefixes
Stesso discorso di prima, la condizione sull'inizio non è indispensabile

2025-01-07 09:37 UTC, jacogasp commented on .gitignore
Stupid question: are those certs (especially the private key) dummy certs only for test, aren't they? Because they are of course still accessible from the git history.
Sorry for the obvious.

2025-01-07 09:39 UTC, jacogasp commented on app/deployments/routes.py
> +from re import match, search
In general, I would prefer to only `import re` and use `re.match` and `re.search`, especially in such a huge file like this one. `match` and `search` are very wide terms that can be associated with a infinite number of things.
Using `re.match` or `re.search` clearly highlights the fact that we are talking about regex

2025-01-07 09:45 UTC, jacogasp commented on app/deployments/routes.py
> +                    "vmProperties"
You're checking that `VirtualMachineInfo` exists but not checking if `vmProperties` exists in that JSON.
Could be ok if it is an always present property, but still dangerous in case of missing key.
Are eventual errors handled?

2025-01-07 09:55 UTC, jacogasp commented on app/deployments/routes.py
> -            sec_group for sec_group in return_sec_group_list if search(substring, sec_group["name"])
This and the previous part are a bit convoluted.
First, the terms `sec_group`, `sec_group_list` and `return_sec_group_list` are not clear names.
I suggest to use simply `sec_group` for the single entity and `sec_groups` to identify the list.
Then, the `return_sec_groups` list is most probably not necessary.

More comments follow below

2025-01-07 10:22 UTC, jacogasp commented on app/deployments/routes.py
> -            sec_group for sec_group in return_sec_group_list if search(substring, sec_group["name"])
```python
return_sec_group_list = [
    sec_group for sec_group in return_sec_group_list if search(substring, sec_group["name"])
    for sec_group in return_sec_group_list
     if search(substring, sec_group["name"])
]
```

This is very convoluted too. First: is regex search `really needed`? We are looking for are simple substring, not a real regex pattern. Before all, rename `substring` to something more clear, like for example `pub_network_key`.
Then, since we are filtering all sec groups that has such key, consider using the `filter` function.

```python

if public:
   return list(filter(lambda sec_group: "pub_network" in sec_group["name"]))
```

2025-01-07 10:23 UTC, jacogasp commented on app/deployments/routes.py
> +            app.logger.error(
Again, sometimes we use `format()` and sometimes we use `f-strings`. Be consistent (I would prefer `f-strings` when possibile)

2025-01-07 10:32 UTC, jacogasp commented on app/deployments/routes.py
> +                sum(1 for res in resources if res.get("toscaNodeName") == node_name) - 1
This `sum` of +1 is pretty bizzare :)
Since we are creating a new list anyway of "ones", instead we can filter the node list and simply get the length

```python
filtered = list(filter(lambda res: res.get("toscaNodeName") == node_name)
count = len(filtered) - 1
```
Are we sure that that "-1" is correct? When we have resources matching the `node_name` that counter has value -1, which is bizarre.

2025-01-07 10:34 UTC, jacogasp commented on app/deployments/routes.py
>          if not form_data.get("extra_opts.force_update") and all(
Very difficult to ready, cannot understand what's happening here

2025-01-07 10:42 UTC, jacogasp commented on app/deployments/routes.py
> -        and (k in stinputs and "updatable" in stinputs[k] and stinputs[k]["updatable"] is True)
Extremely hard to ready, no clue about what is going on.
`stinputs[k]["updatable"] is True` this is useless, we are checking a boolean expression in a if statement. We can simply write `if (... and stinputs[k]["updatable"] and ...)`

Then, the are really really really to many `and`, but REALLY to many!!!
We can easily loose the control of the branching logic because there are REALLY to many branches.

To simplify, consider to use early returns or something similar, for example:

```python
for k, v in form_data.items() # no braces are required for the tuple
    if "updatable" not in stinputs[k]:
       continue   # since is not updatable we can continue directly to the next item
    # do stuff
```
Moreover, we are evaluating the same conditions (is updatable) twice for nothing

2025-01-07 10:42 UTC, jacogasp commented on app/deployments/routes.py
> +    keep_last_attempt = (
Not sure the braces are required

2025-01-07 10:44 UTC, jacogasp commented on app/deployments/routes.py
> +        flash("Error retrieving deployment list: \n" + str(e), "warning")
Why is a warning but we say "error"? :)

2025-01-07 10:47 UTC, jacogasp commented on app/deployments/routes.py
> +    inputs = process_deployment_data(dep)[0]
What if the result of `process_deployment_data(dep)` returns an empty list?

2025-01-07 10:49 UTC, jacogasp commented on app/deployments/routes.py
> +    if deployments:
Quite bizarre to write only one line inside the `try except` block. Maybe but everything that needs the `deployments` variable inside the `try/except`, or consider to move it inside the `app.orchestrator.get_deployment` method

2025-01-07 10:50 UTC, jacogasp commented on app/deployments/routes.py
> +                num_retry = int(tmp_dep.description.split(str_retry)[1])
What if the split returns a list with length < 2?

2025-01-07 10:51 UTC, jacogasp commented on app/deployments/routes.py
> +    additionaldescription = tmp_name + str_retry + str(max_num_retry + 1)
Consider `f-string`: `desc = f"{tmp_name}{str_retry}{max_num_retry + 1}"`

2025-01-07 10:53 UTC, jacogasp commented on app/deployments/routes.py
> +        if search("bucket_name", name):
Same as above, if we are just searching for a substring withing a string, use ` if my_substring in substring:`

2025-01-07 10:55 UTC, jacogasp commented on app/deployments/routes.py
> +            if errors:
This is not necessary. In any case, if I understand correctly, the method `check_s3_bucket_name` return ALWAYS a list, empty if no errors occurred.
If this is the case, we can simply iterate over an empty list `for error in errors`

2025-01-07 10:58 UTC, jacogasp commented on app/deployments/routes.py
> +                return redirect(url_for(SHOW_DEPLOYMENTS_ROUTE))
Always if I understand well, if the `errors` is ALWAYS a valid list (even though empty), this `return redirect(...)` is always called. If this is the case, change

```python
if errors:
    # do stuff
```

with

```python
if len(errors) > 0:
    # do stuff
```

2025-01-07 11:01 UTC, jacogasp commented on app/deployments/templates/createdep.html
> +		if (!this.disabled) {
A lot of nested if/else if. Could we reorganize all those `if`s?

2025-01-07 11:14 UTC, jacogasp commented on app/deployments/templates/input_types.html
> +        errors.push(1);
This logic is really bad (continue below)

2025-01-07 11:14 UTC, jacogasp commented on app/deployments/templates/input_types.html
> +	if(errors.length == 0) {
This line is not vertically aligned

2025-01-07 11:19 UTC, jacogasp commented on app/deployments/templates/input_types.html
> +						<li id="rule_1_{{key}}">Bucket names must be between 1 and 27 characters long.</li>
Please start counting from 0

2025-01-07 11:41 UTC, jacogasp commented on app/deployments/templates/input_types.html
> +		if(!errors.includes(i)) {
This is really bad:

`includes` is a linear search and thus an entire loop. So we have two nested loops, and thus again a O(n^2) operation. 
In this case, with very few elements (exactly 7) most probably performance is not an issue, but still this logic is pretty ugly.
First, do not hardcode loop ranges in this way (why from 1 and not 0, and why up to 7? It is not clear to the reader); second, the `includes` call is completely not necessary.
In total we have three loops, two of which nested:
- one to iterate over each rule
- one to search if the rules has an error
- one to make all the other rules green

In total we have a complexity of O(2*n^2).

We can do something like:

```js
const rules = [
  (name) => name.includes("foo"),
  (name) => !/^[a-z0-9.-]+$/.test(name),
  ...
 ];
 
rules.forEach((rule, index) => {
    const isValid = rule(); 
   $(`#rule_${index}_${elem_id}`).css({color: isValid ? "green" : "red"});
});
```
In this case we can do everything with just one loop

2025-01-07 11:43 UTC, jacogasp commented on app/home/static/js/script-v2.js
> +        let label = $($(element).children()[0]);
You const ALWAYS. Should be the default option to declare a variable. Use let only when it needs to be mutated.

2025-01-07 11:44 UTC, jacogasp commented on app/home/static/js/script-v2.js
> +            label.text(text + ' (' + chars + '/' + maxlength + ')');
```js
label.text(`${text} (${chars}/${maxLength})`)
```

2025-01-07 11:45 UTC, jacogasp commented on app/home/static/js/script-v2.js
> +            if (e.type == 'summernote') {
`if (e.type === 'summernote')`

2025-01-07 11:54 UTC, jacogasp commented on app/deployments/routes.py
> +    access_token = iam.token["access_token"]
What if we don't have the "access_token" key? Should we use `try/catch` of some guard clause to raise an exception if we don't have the token?

2025-01-13 13:26 UTC, ettore-infn commented on .gitignore
Yes they are certs for tests purpose only. I accidentally committed them because when I initialized the repository my .gitignore wasn't correctly aligned with the certs names.

2025-01-17 11:03 UTC, ettore-infn commented on app/deployments/routes.py
> +            if errors:
I need the IF to redirect the user to the deployments page and terminate the method only if an error occurs

2025-01-21 14:44 UTC, giosava94 approved these changes

2025-01-24 15:02 UTC, merged